server:
  port: 8003

spring:
  application:
    name: report-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/crash_reports
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

auth:
  service:
    url: http://localhost:8002

ml:
  service:
    url: http://localhost:8004
